CREATE MATERIALIZED VIEW VW_ACCOUNT_INFORMATION
  NOLOGGING
  CACHE
  BUILD IMMEDIATE
  REFRESH FAST ON COMMIT 
AS
SELECT 
	MC.ID AS CUSTOMER_ID, 
	MC.CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
	MC.CUSTOMER_TYPE AS CUSTOMER_TYPE,
	MC.CUSTOMER_NAME AS CUSTOMER_NAME,
	MC.CUSTOMER_IDENTIFICATION_NUMBER AS CUSTOMER_IDENTIFICATION_NUMBER,
	MC.IDENTIFICATION_TYPE AS CUSTOMER_IDENTIFICATION_TYPE,
	MC.SEX AS SEX,
  MC.FOUNDED_BIRTH_DATE AS FOUNDED_BIRTH_DATE,
  MC.FOUNDED_BIRTH_PLACE AS FOUNDED_BIRTH_PLACE,
  MC.MARITAL_STATUS AS MARITAL_STATUS,
  MC.STATUS AS CUSTOMER_STATUS,
  MC.SEARCH_KEY AS SEARCH_KEY,
  MA.ID AS ACCOUNT_ID,
  MA.REGISTRATION_NUMBER AS REGISTRATION_NUMBER,
  MA.ACCOUNT_GROUP AS ACCOUNT_GROUP,
  MA.ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
  MA.ACCOUNT_NAME AS ACCOUNT_NAME,
  MA.ACCOUNT_SEGMENT AS ACCOUNT_SEGMENT,
  MA.ACCOUNT_GROUP_TYPE AS ACCOUNT_GROUP_TYPE,
  MA.ACCOUNT_CATEGORY AS ACCOUNT_CATEGORY,
  MA.ACCOUNT_RULE_ID AS CLASSIFICATION_TYPE,
  MA.ACCOUNT_TYPE AS ACCOUNT_TYPE,
  MA.PAYMENT_CHANNEL AS PAYMENT_CHANNEL,
  MA.DESCRIPTION AS ACCOUNT_DESCRIPTION,
  MA.SOR AS SOR,
  MA.COST_CENTER AS COST_CENTER,
  MA.METER_READING_CODE AS METER_READING_CODE,
  MA.INDUSTRIAL_SECTOR AS INDUSTRIAL_SECTOR,
  MA.BUDGET_YEAR AS BUDGET_YEAR,
  MA.BUDGET AS BUDGET,
  MA.TERITORY AS TERITORY,
  mti.TAX_IDENTIFIER_TYPE AS M_TAX_IDENTIFIER_TYPE,
  mti.TAX_IDENTIFIER_NUMBER AS M_TAX_IDENTIFIER_NUMBER,
  mti.TAX_IDENTIFIER_NAME AS M_TAX_IDENTIFIER_NAME,
  mti.TAX_IDENTIFIER_ADDRESS AS M_TAX_IDENTIFIER_ADDRESS,
  mti.TAX_IDENTIFIER_TYPE AS TAX_RELATION_IDENTIFIER_TYPE,
  mti.TAX_IDENTIFIER_NUMBER AS TAX_RELATION_IDENTIFIER_NUMBER,
  mti.TAX_IDENTIFIER_NAME AS TAX_RELATION_IDENTIFIER_NAME,
  mti.TAX_IDENTIFIER_ADDRESS AS TAX_RELATION_IDENTIFIER_ADDRESS,
  MA.PRIORITY AS PRIORITY,
  MA.IS_CORPORATE AS IS_CORPORATE,
  MA.IS_EXCEPTION AS IS_EXCEPTION,
  MA.IS_BAD_DEBT AS IS_BAD_DEBT,
  MA.SYNC_FLAG AS IS_SYNC,
  MA.ACCOUNT_REFERENCE_ID AS ACCOUNT_REFERENCE_ID,
  MA.ENTITY_ID AS ENTITY_ID,
  MA.STATUS AS ACCOUNT_STATUS,
  MA.CUSTOMER_ID AS ACCOUNT_CUSTOMER_ID
FROM 
	M_CUSTOMER mc, M_ACCOUNT ma, M_TAX_IDENTIFIER mti
WHERE 
	MC.ID = MA.CUSTOMER_ID;
	