package com.dbs.database.crm.entities.report;

import com.dbs.common.base.entities.DefaultBaseEntities;
import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

@Entity
@Data
@Table(name = "VW_REPORT_CUSTOMER")
public class VW_REPORT_CUSTOMER extends DefaultBaseEntities {
    @Id
    @Column(name = "SEQUENCE")
    private Integer sequence;
    @Column(name = "CUSTOMER_ID")
    private Integer customerId;
    @Column(name = "ACCOUNT_ID")
    private Integer accountId;
    @Column(name = "CUSTOMER_NUMBER")
    private String customerNumber;
    @Column(name = "CUSTOMER_NAME")
    private String customerName;
    @Column(name = "CUSTOMER_TYPE")
    private String customerType;
    @Column(name = "CUSTOMER_STATUS")
    private String customerStatus;
    @Column(name = "CUSTOMER_IDENTIFICATION_TYPE")
    private String customerIdentificationType;
    @Column(name = "CUSTOMER_IDENTIFICATION_NUMBER")
    private String customerIdentificationNumber;
    @Column(name = "CUSTOMER_DESCRIPTION")
    private String customerDescription;
    @Column(name = "SOR")
    private String sor;
    @Column(name = "COST_CENTER")
    private String costCenter;
    @Column(name = "AREA_CODE")
    private String areaCode;
    @Column(name = "ACCOUNT_NUMBER")
    private String accountNumber;
    @Column(name = "REGISTRATION_NUMBER")
    private String registrationNumber;
    @Column(name = "ACCOUNT_NAME")
    private String accountName;
    @Column(name = "METER_READING_CODE")
    private String meterReadingCode;
    @Column(name = "TERITORY")
    private String teritory;
    @Column(name = "ACCOUNT_SEGMENT")
    private String accountSegment;
    @Column(name = "ACCOUNT_GROUP_TYPE")
    private String accountGroupType;
    @Column(name = "ACCOUNT_CATEGORY")
    private String accountCategory;
    @Column(name = "CLASSIFICATION_TYPE")
    private String classificationType;
    @Column(name = "ACCOUNT_TYPE")
    private String accountType;
    @Column(name = "JENIS_REKENING")
    private String jenisRekening;
    @Column(name = "INDUSTRIAL_SECTOR")
    private String industrialSector;
    @Column(name = "ACCOUNT_STATUS")
    private String accountStatus;
    @Column(name = "PRIORITY")
    private String priority;
    @Column(name = "DATE_AGREEMENT")
    private Date dateAgreement;
    @Column(name = "DATE_GAS_IN")
    private Date dateGasIn;
    @Column(name = "DATE_UNSUBCRIPTION")
    private Date dateUnsubcription;
    @Column(name = "GAS_SOURCE")
    private String gasSource;
    @Column(name = "SERVICE_TYPE")
    private String serviceType;
    @Column(name = "BUDGET")
    private String budget;
    @Column(name = "BUDGET_YEAR")
    private String budgetYear;
    @Column(name = "CUSTOMER_MANAGEMENT_NAME")
    private String customerManagementName;
    @Column(name = "MONTHLY_TURNOVER")
    private String monthlyTurnover;
    @Column(name = "CEO")
    private String ceo;
    @Column(name = "COMPANY_GROUP")
    private String companyGroup;
    @Column(name = "IS_CORPORATE")
    private String isCorporate;
    @Column(name = "IS_EXCEPTION")
    private String isException;
    @Column(name = "PREPAID")
    private String prepaid;
    @Column(name = "CALORIE_TYPE")
    private String calorieType;
    @Column(name = "ACCOUNT_DESCRIPTION")
    private String accountDescription;
    @Column(name = "NONORGANIC_WORKERS")
    private String nonorganicWorkers;
    @Column(name = "OWNERSHIP")
    private String ownership;
    @Column(name = "MAIN_PH_NUM")
    private String mainPhNum;
    @Column(name = "VA_STATUS")
    private String vaStatus;
    @Column(name = "WORKINGDAY_PER_WEEKS")
    private String workingdayPerWeeks;
    @Column(name = "WORKINGHOUR_PER_DAY")
    private String workinghourPerDay;
    @Column(name = "EMAIL")
    private String email;
    @Column(name = "WEBSITE")
    private String website;
    @Column(name = "CONTACT_NAME")
    private String contactName;
    @Column(name = "FIRST_NAME")
    private String firstName;
    @Column(name = "MIDDLE_NAME")
    private String middleName;
    @Column(name = "LAST_NAME")
    private String lastName;
    @Column(name = "CONTACT_ADDRESS")
    private String contactAddress;
    @Column(name = "CELLPHONE")
    private String cellphone;
    @Column(name = "HOMEPHONE")
    private String homephone;
    @Column(name = "PHONENUMBER")
    private String phonenumber;
    @Column(name = "FAXNUMBER")
    private String faxnumber;
    @Column(name = "CONTACT_PERSON")
    private String contactPerson;
    @Column(name = "JOB_NAME")
    private String jobName;
    @Column(name = "POSITION_NAME")
    private String positionName;
    @Column(name = "ADDITIONAL_NOTE")
    private String additionalNote;
    @Column(name = "DESCRIPTION")
    private String description;
    @Column(name = "STATUS")
    private String status;
    @Column(name = "PRIMARY_FLAG")
    private String primaryFlag;
    @Column(name = "FULL_ADDRESS")
    private String fullAddress;
    @Column(name = "ADDRESS")
    private String address;
    @Column(name = "TYPE")
    private String type;
    @Column(name = "BUILDING")
    private String building;
    @Column(name = "HOUSE_NAME")
    private String houseName;
    @Column(name = "STREET_NAME")
    private String streetName;
    @Column(name = "BLOCK")
    private String block;
    @Column(name = "HOUSE_NUMBER")
    private String houseNumber;
    @Column(name = "RT")
    private String rt;
    @Column(name = "RW")
    private String rw;
    @Column(name = "SUB_DISTRICT")
    private String subDistrict;
    @Column(name = "DISTRICT")
    private String district;
    @Column(name = "CITY")
    private String city;
    @Column(name = "PROVINCE")
    private String province;
    @Column(name = "POSTAL_CODE")
    private String postalCode;
    @Column(name = "COUNTRY")
    private String country;
    @Column(name = "LONGITUDE")
    private String longitude;
    @Column(name = "LATITUDE")
    private String latitude;
    @Column(name = "ALTITUDE")
    private Float altitude;
    @Column(name = "PREMISE_FLAG")
    private String premiseFlag;
    @Column(name = "TAX_IDENTIFIER_NUMBER")
    private String taxIdentifierNumber;
    @Column(name = "TAX_IDENTIFIER_NAME")
    private String taxIdentifierName;
    @Column(name = "TAX_IDENTIFIER_ADDRESS")
    private String taxIdentifierAddress;
    @Column(name = "TAX_RELATION_IDENTIFIER_TYPE")
    private String taxRelationIdentifierType;
    @Column(name = "TAX_RELATION_IDENTIFIER_NUMBER")
    private String taxRelationIdentifierNumber;
    @Column(name = "TAX_RELATION_IDENTIFIER_NAME")
    private String taxRelationIdentifierName;
    @Column(name = "TAX_RELATION_IDENTIFIER_ADDRESS")
    private String taxRelationIdentifierAddress;
    @Column(name = "PAYMENT_CHANNEL")
    private String paymentChannel;
    @Column(name = "IS_BAD_DEBT")
    private String isBadDebt;
    @Column(name = "IS_SYNC")
    private String isSync;

}
