package com.dbs.module.account.master.meterreadingcodes.service;

import com.dbs.common.base.utils.Constant;
import com.dbs.common.base.utils.MaterialTablePagingRequest;
import com.dbs.common.base.utils.PagingUtils;
import com.dbs.common.base.utils.ResponseUtils;
import com.dbs.common.library.config.jwt.JwtUtils;
import com.dbs.common.library.ctrl.ResponseObject;
import com.dbs.common.library.utils.*;
import com.dbs.common.library.services.GlobalTypeValueService;
import com.dbs.database.crm.entities.accountmanagement.M_ACCOUNT;
import com.dbs.database.crm.entities.accountmanagement.M_METER_READING_CODES;
import com.dbs.database.crm.entities.ratingbillinginvoice.view.VW_ACCOUNT_INFORMATION;
import com.dbs.database.crm.entities.usermanagement.*;
import com.dbs.database.crm.repositories.accountmanagement.Account.MAccountRepo;
import com.dbs.database.crm.repositories.accountmanagement.Account.MMeterReadingCodesRepo;
import com.dbs.database.crm.repositories.usermanagement.AuditTrailRepo;
import com.dbs.database.crm.repositories.usermanagement.MCostCenterRepo;
import com.dbs.database.crm.repositories.usermanagement.MPositionRepo;
import com.dbs.database.crm.repositories.usermanagement.MUserRepo;
import com.dbs.database.crm.utils.CostCenterUtils;
import com.dbs.module.account.main.dto.NameValueDdlResponseDto;
import com.dbs.module.account.master.meterreadingcodes.dto.CreateRequestDTO;
import com.dbs.module.account.master.meterreadingcodes.dto.UpdateRequestDTO;
import com.dbs.module.account.master.meterreadingcodes.dto.ActiveInactiveDTO;
import java.io.ByteArrayInputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;
import javax.servlet.http.HttpServletRequest;
import javax.validation.ConstraintViolation;
import javax.validation.Validator;

import com.dbs.module.account.utils.ConstantAccount;
import com.dbs.module.account.utils.UtilsAccount;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.InputStreamResource;
import org.springframework.data.domain.Page;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.data.web.PagedResourcesAssembler;
import org.springframework.hateoas.EntityModel;
import org.springframework.hateoas.PagedModel;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.ObjectUtils;

import static com.dbs.common.base.utils.CommonHelper.removeSpace;
import static com.dbs.common.base.utils.Constant.GET_CC_CHILD;
import static com.dbs.common.library.utils.StringUtils.capitalizeFully;
import static org.apache.commons.lang3.StringUtils.isNotBlank;


@Service
public class MeterReadingCodesService {
    private static final Logger logger = LoggerFactory.getLogger(MeterReadingCodesService.class);
    
    private final MMeterReadingCodesRepo meterRepo;
    private final Validator validator;
    private final AuditTrailRepo auditTrailRepo;
    private final MUserRepo mUserRepo;
    
    @Autowired
    private AutoGeneratedCode autoGeneratedCode;
    
    @Autowired
    private MPositionRepo mPositionRepo;
    
    @Autowired
    private JwtUtils jwtUtils;

    @Autowired 
    private GlobalTypeValueService globalTypeService;
    @Autowired
    private MAccountRepo mAccountRepo;
    @Autowired
    private MCostCenterRepo mCostCenterRepo;
    @Autowired
    private ObjectMapper objectMapper;
    
    public MeterReadingCodesService(MMeterReadingCodesRepo meterRepo, Validator validator, AuditTrailRepo auditTrailRepo, MUserRepo mUserRepo) {
        this.meterRepo = meterRepo;
        this.validator = validator;
        this.auditTrailRepo = auditTrailRepo;
        this.mUserRepo = mUserRepo;
    }
    @SuppressWarnings({"java:S1192"})
    public ResponseEntity<ResponseObject> create(CreateRequestDTO request, HttpServletRequest httpServletRequest) {
        try {

            ResponseEntity<ResponseObject> validate = this.validateCreate(Boolean.FALSE, request, httpServletRequest);
            if(StringUtils.hasValue(validate)) {
                return validate;
            }

            M_METER_READING_CODES newMeter = new M_METER_READING_CODES();
            Optional<M_COSTCENTER> getNameCC = mCostCenterRepo.findByCcIdAndStatusAndIsDeleted(request.getCostCenterId(), FlowStatus.ACTIVE.name(), Boolean.FALSE);
            newMeter.setCostCenter(getNameCC.isPresent()?getNameCC.get().getCode()+" - "+getNameCC.get().getName():null);
            newMeter.setCode(request.getCode().strip());
            newMeter.setCostCenterId(request.getCostCenterId());
            newMeter.setEntityId(UserDetailUtils.getUserEntity());
            newMeter.setDescription(request.getDescription());
            newMeter.setCreatedBy(UserDetailUtils.getUsername());
            newMeter.setStatus(FlowStatus.ACTIVE.name());
            newMeter.setCreatedDate(new Date());
            meterRepo.save(newMeter);

            return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_TRUE, HttpStatus.CREATED,
                    UtilsAccount.messageSuccess(ConstantAccount.CREATE, ConstantAccount.MASTER_METERREADINGCODE), newMeter), HttpStatus.CREATED);
        } catch (Exception e) {
            logger.error(Constant.LOG_ERROR, e.getMessage(), e);
            return new ResponseEntity<>(
                    new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.INTERNAL_SERVER_ERROR,
                            ResponseUtils.MESSAGE_INTERNAL_SERVER_ERROR, null),
                    HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    public ResponseEntity<ResponseObject> validateCreate(Boolean api, CreateRequestDTO request, HttpServletRequest httpServletRequest) {
        try {
            var violations = validator.validate(request);
            if (!violations.isEmpty()) {
                List<Map<String, Object>> violationHeaderList = new ArrayList<>();
                List<String> validateHeader = new ArrayList<>();
                for (var violation : violations) {
                    logger.error(violation.getMessage());
                    Map<String, Object> data = new HashMap<>();
                    validateHeader.add(violation.getMessage());
                    data.put(violation.getPropertyPath().toString(), violation.getMessage());
                    violationHeaderList.add(data);
                }
                ResponseObject result = new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.BAD_REQUEST, validateHeader.get(0), violationHeaderList);
                return new ResponseEntity<>(result, result.getHttpCode());
            }

            if (meterRepo.existsByCodeIgnoreCaseAndCostCenterId(removeSpace(request.getCode()), request.getCostCenterId())) {
                return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.BAD_REQUEST,
                        "Meter Reading Codes already exist!", ResponseUtils.DATA_EMPTY), HttpStatus.BAD_REQUEST);
            }

            return UtilsAccount.returnForValidateOrApi(api, ConstantAccount.MASTER_METERREADINGCODE);

        } catch (Exception e) {
            logger.error(Constant.LOG_ERROR, e.getMessage(), e);
            return new ResponseEntity<>(
                    new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.INTERNAL_SERVER_ERROR,
                            ResponseUtils.MESSAGE_INTERNAL_SERVER_ERROR, null),
                    HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    @SuppressWarnings({"java:S1192"})
    public ResponseEntity<ResponseObject> getList(MaterialTablePagingRequest pagingData,
                                                     PagedResourcesAssembler<M_METER_READING_CODES> assembler, HttpServletRequest httpServletRequest) {
        try {
            CostCenterUtils costCenterUtils = new CostCenterUtils();
            Map<String, Object> filter = new HashMap<>();
            filter.put("positionId", UserDetailUtils.getPositionFromToken(httpServletRequest));

            if (isNotBlank(pagingData.getSearchs())) {
                Map<String, Object> searchMap = objectMapper.readValue(pagingData.getSearchs(), HashMap.class);
                for (Map.Entry<String, Object> entry : searchMap.entrySet()) {
                    String key = entry.getKey();
                    Object value = entry.getValue();
                    pagingData.getSearch().add(key+"~"+value);
                }
            }

            Specification<M_METER_READING_CODES> specification = pagingData.getSearch().isEmpty()
                    ? meterRepo.getSpecificationDefault(filter)
                    : meterRepo.getSpecificationFromFilters(pagingData, filter);

            Page<M_METER_READING_CODES> data = meterRepo.findAll(specification, PagingUtils.getPaging(pagingData));

            List<LinkedHashMap<String, Object>> allData = data.getContent().stream()
                    .map(g -> {
                        LinkedHashMap<String, Object> meterCode = new LinkedHashMap<>();
                        meterCode.put("id", g.getMeterReadingCodeId());
                        meterCode.put("code", g.getCode());
                        meterCode.put("costCenterId", g.getCostCenterId());
                        meterCode.put("costCenter", g.getCostCenter());
                        meterCode.put("description", g.getDescription());
                        meterCode.put("status", g.getStatus());
                        
                        meterCode.put("entityId", g.getEntityId());

                        meterCode.put("createdBy", g.getCreatedBy());
                        meterCode.put("createdDate", g.getCreatedDate());
                        meterCode.put("updatedBy", g.getUpdatedBy());
                        meterCode.put("UpdatedDate", g.getUpdatedDate());
                        return meterCode;
                    })
                    .collect(Collectors.toList());

            PagedModel<EntityModel<M_METER_READING_CODES>> pagedData = assembler.toModel(data);
            Map<String, Object> d = new HashMap<>();
            d.put(Constant.RESULT, allData);
            d.put(Constant.PAGE, pagedData.getMetadata());
            d.put(Constant.LINK, pagedData.getLinks());
            return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_TRUE, HttpStatus.OK,
                    "Success get view paging", d), HttpStatus.OK);
        } catch (Exception e) {
            logger.error(Constant.LOG_ERROR, e.getMessage(), e);
            return new ResponseEntity<>(
                    new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.INTERNAL_SERVER_ERROR,
                            ResponseUtils.MESSAGE_INTERNAL_SERVER_ERROR, null),
                    HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    public ResponseEntity<InputStreamResource> downloadFilter(MaterialTablePagingRequest pagingData, HttpServletRequest httpServletRequest) {
        try {
            CostCenterUtils costCenterUtils = new CostCenterUtils();
            Page<M_METER_READING_CODES> data;
            Map<String, Object> filter = new HashMap<>();
            filter.put("costCenterId", costCenterUtils.findCostCenterByPositionId(UserDetailUtils.getPositionFromToken(httpServletRequest)));
            if (isNotBlank(pagingData.getSearchs())) {
                Map<String, Object> searchMap = objectMapper.readValue(pagingData.getSearchs(), HashMap.class);
                for (Map.Entry<String, Object> entry : searchMap.entrySet()) {
                    String key = entry.getKey();
                    Object value = entry.getValue();
                    pagingData.getSearch().add(key+"~"+value);
                }
            }
            if (pagingData.getPage() != null && pagingData.getSize() != null) {

                long maxData = StreamSupport.stream(meterRepo.findAll().spliterator(), false).count();
                pagingData.setSize((int) maxData);
                pagingData.setPage(1);

            }
            if (!pagingData.getSearch().isEmpty()) {
                data = this.meterRepo.findAll(this.meterRepo.getSpecificationFromFilters(pagingData, filter),
                        PagingUtils.getPaging(pagingData));
            } else {
                data = this.meterRepo.findAll(this.meterRepo.getSpecificationDefault(filter),
                        PagingUtils.getPaging(pagingData));
            }
            List<M_METER_READING_CODES> listAction = data.getContent();
            List<LinkedHashMap<String, Object>> allData = new ArrayList<>();
            Integer no = 1;
            HttpHeaders headers = new HttpHeaders();
            if(data.hasContent()) {
                for (M_METER_READING_CODES a : listAction) {
                    LinkedHashMap<String, Object> response = new LinkedHashMap<>();
                    response.put("NO", no);
                    response.put("COST CENTER", a.getCostCenter());
                    response.put("CODE", a.getCode());
                    response.put("DESCRIPTION", a.getDescription());
                    response.put("STATUS", capitalizeFully(a.getStatus()));
                    allData.add(response);
                    no = no + 1;
                }
                ByteArrayInputStream in = DownloadToExcel.downloadsFiles(allData, "Excel");
                headers.add(Constant.CONTENT_DISPOSITION, "attachment; filename=" +
                        "METER_READING_CODES_" + UtilsDate.dateToString(new Date(), "yyyyMMddHHmmss") + ".xlsx");
                return ResponseEntity.ok().headers(headers).body(new InputStreamResource(in));
            } else {
                headers.add(Constant.CONTENT_DISPOSITION, "No Data");
                return ResponseEntity.noContent().build();
            }
        } catch (Exception e) {
            logger.info(String.format(CommonVariables.ERROR_IN_PAR, e.getMessage()));
            e.printStackTrace();
            return ResponseEntity.internalServerError().body(null);
        }
    }
    
    public ResponseEntity<ResponseObject> getDetail(Integer meterReadingCodeId) {
        try {
            Optional<M_METER_READING_CODES> mMeter = meterRepo.findByMeterReadingCodeId(meterReadingCodeId);
            if (mMeter.isPresent()) {
                M_METER_READING_CODES data = mMeter.get();
                LinkedHashMap<String, Object> response = new LinkedHashMap<>();
                response.put("id", data.getMeterReadingCodeId());
                response.put("code", data.getCode());
                response.put("costCenterId", data.getCostCenterId());
                response.put("costCenter", data.getCostCenter());
                response.put("description", data.getDescription());
                response.put("entityId", data.getEntityId());
                response.put("status", data.getStatus());
                response.put("createdBy", data.getCreatedBy());
                response.put("createdDate", data.getCreatedDate());
                response.put("updatedBy", data.getUpdatedBy());
                response.put("updatedDate", data.getUpdatedDate());

                //acr
                List<AUDIT_TRAIL> auditTrail = auditTrailRepo.findAll().stream()
                        .filter(e -> e.getTableName().equalsIgnoreCase("M_METER_READING_CODES"))
                        .filter(f -> f.getDataId().equalsIgnoreCase(data.getMeterReadingCodeId().toString()))
                        .collect(Collectors.toList());
                response.put("activeInactiveLog", auditTrail);

                return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_TRUE, HttpStatus.OK,
                        "Success get detail meter reading codes", response), HttpStatus.OK);
            } else {
                return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.NOT_FOUND,
                        "meter reading codes not found", ResponseUtils.DATA_EMPTY), HttpStatus.NOT_FOUND);
            }
        } catch (Exception e) {
            logger.error(Constant.LOG_ERROR, e.getMessage(), e);
            return new ResponseEntity<>(
                    new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.INTERNAL_SERVER_ERROR,
                            ResponseUtils.MESSAGE_INTERNAL_SERVER_ERROR, null),
                    HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
    
    public ResponseEntity<ResponseObject> activeInactive(ActiveInactiveDTO request) {
        ResponseObject result;
        try {
            List<M_ACCOUNT> lisAccount = mAccountRepo.findAllByMeterReadingCode(request.getMeterReadingCodeId());
            if(!lisAccount.isEmpty()){
                result = new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.BAD_REQUEST,
                        "You can't inactivate meter reading code. This meter reading code used by customer account.", null);
                return new ResponseEntity<>(result, result.getHttpCode());
            }
            Optional<M_METER_READING_CODES> mMeter = meterRepo.findByMeterReadingCodeId(request.getMeterReadingCodeId());
            if (mMeter.isPresent()) {
                M_METER_READING_CODES data = mMeter.get();
                LinkedHashMap<String, Object> oldGasSource = new LinkedHashMap<>();
                oldGasSource.put("id", data.getMeterReadingCodeId());
                oldGasSource.put("code", data.getCode());
                oldGasSource.put("costCenterId", data.getCostCenterId());
                oldGasSource.put("description", data.getDescription());
                oldGasSource.put("entityId", data.getEntityId());
                oldGasSource.put("status", data.getStatus());
                AUDIT_TRAIL auditTrail = new AUDIT_TRAIL();
                ObjectMapper mapper = new ObjectMapper();
                String oldValue = mapper.writeValueAsString(oldGasSource);
                auditTrail.setOldValue(oldValue);
                auditTrail.setRemark(request.getRemark());
                auditTrail.setTableName("M_METER_READING_CODES");
                auditTrail.setDataId(data.getMeterReadingCodeId().toString());
                Optional<M_USER> user = mUserRepo.findByUsername(UserDetailUtils.getUsername());
                if (user.isEmpty()) {
                    result = new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.BAD_REQUEST,
                            "user with username " + UserDetailUtils.getUsername() + " not found", ResponseUtils.DATA_EMPTY);
                    return new ResponseEntity<>(result, result.getHttpCode());
                }
                R_GLOBAL_TYPE_VALUE rUserLevel = globalTypeService.getGlobalTypeByGlbValue(Constant.USER_LEVEL, user.get().getUserLevel());
                String userLevel = rUserLevel.getName() != null ? rUserLevel.getName() : "";
                auditTrail.setUserLevel(userLevel);
                auditTrail.setCreatedBy(UserDetailUtils.getUsername() != null ? UserDetailUtils.getUsername() : null);
                auditTrail.setCreatedDate(new Date());
                if (data.getStatus().equalsIgnoreCase(FlowStatus.INACTIVE.name())) {
                    data.setStatus(FlowStatus.ACTIVE.name());
                    data.setUpdatedBy(UserDetailUtils.getUsername());
                    data.setUpdatedDate(new Date());
                    M_METER_READING_CODES saveMeter = meterRepo.save(data);
                    LinkedHashMap<String, Object> newMeter = new LinkedHashMap<>();
                    newMeter.put("id", saveMeter.getMeterReadingCodeId());
                    newMeter.put("code", saveMeter.getCode());
                    newMeter.put("costCenterId", saveMeter.getCostCenterId());
                    newMeter.put("description", saveMeter.getDescription());
                    newMeter.put("entityId", saveMeter.getEntityId());
                    newMeter.put("status", saveMeter.getStatus());
                    String newValue = mapper.writeValueAsString(newMeter);
                    auditTrail.setNewValue(newValue);
                    auditTrail.setOperation(FlowStatus.ACTIVE.name());
                    auditTrailRepo.save(auditTrail);
                    return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_TRUE, HttpStatus.OK,
                            ResponseUtils.MESSAGE_ACTIVE, ResponseUtils.DATA_EMPTY), HttpStatus.OK);
                }
                data.setStatus(FlowStatus.INACTIVE.name());
                data.setUpdatedBy(UserDetailUtils.getUsername());
                data.setUpdatedDate(new Date());
                M_METER_READING_CODES saveMeter = meterRepo.save(data);
                LinkedHashMap<String, Object> newMeter = new LinkedHashMap<>();
                newMeter.put("id", saveMeter.getMeterReadingCodeId());
                newMeter.put("code", saveMeter.getCode());
                newMeter.put("costCenterId", saveMeter.getCostCenterId());
                newMeter.put("description", saveMeter.getDescription());
                newMeter.put("entityId", saveMeter.getEntityId());
                newMeter.put("status", saveMeter.getStatus());
                String newValue = mapper.writeValueAsString(newMeter);
                auditTrail.setNewValue(newValue);
                auditTrail.setOperation(FlowStatus.INACTIVE.name());
                auditTrailRepo.save(auditTrail);
                return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_TRUE, HttpStatus.OK,
                        ResponseUtils.MESSAGE_INACTIVE, ResponseUtils.DATA_EMPTY), HttpStatus.OK);
            } else {
                return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.NOT_FOUND,
                        "Meter reading code not found", ResponseUtils.DATA_EMPTY), HttpStatus.NOT_FOUND);
            }
        } catch (Exception e) {
            logger.error(Constant.LOG_ERROR, e.getMessage(), e);
            return new ResponseEntity<>(
                    new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.INTERNAL_SERVER_ERROR,
                            ResponseUtils.MESSAGE_INTERNAL_SERVER_ERROR, null),
                    HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
    
    @Transactional(rollbackFor = Exception.class, readOnly = false)
    public ResponseEntity<ResponseObject> update(UpdateRequestDTO request, HttpServletRequest httpServletRequest) {
        ResponseObject result;
        try {

            ResponseEntity<ResponseObject> validate = this.validateUpdate(Boolean.FALSE, request, httpServletRequest);
            if(StringUtils.hasValue(validate)) {
                return validate;
            }

            Optional<M_METER_READING_CODES> mMeter = meterRepo.findByMeterReadingCodeId(request.getMeterReadingCodeId());
            M_METER_READING_CODES meterReading = mMeter.get();
            Optional<M_COSTCENTER> getNameCC = mCostCenterRepo.findByCcIdAndStatusAndIsDeleted(request.getCostCenterId(), FlowStatus.ACTIVE.name(), Boolean.FALSE);
            meterReading.setCostCenter(getNameCC.isPresent()?getNameCC.get().getCode()+" - "+getNameCC.get().getName():null);
            meterReading.setCode(request.getCode().strip());
            meterReading.setCostCenterId(request.getCostCenterId());
            meterReading.setDescription(request.getDescription());
            meterReading.setEntityId(UserDetailUtils.getUserEntity());
            meterReading.setUpdatedBy(UserDetailUtils.getUsername());
            meterReading.setUpdatedDate(new Date());
            meterRepo.save(meterReading);

            result = new ResponseObject(ResponseUtils.SUCCESS_TRUE, HttpStatus.OK,
                    UtilsAccount.messageSuccess(ConstantAccount.UPDATE, ConstantAccount.MASTER_METERREADINGCODE), meterReading);

            return new ResponseEntity<>(result, result.getHttpCode());
        } catch (Exception e) {
            logger.error(Constant.LOG_ERROR, e.getMessage(), e);
            return new ResponseEntity<>(
                    new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.INTERNAL_SERVER_ERROR,
                            ResponseUtils.MESSAGE_INTERNAL_SERVER_ERROR, null),
                    HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    public ResponseEntity<ResponseObject> validateUpdate(Boolean api, UpdateRequestDTO request, HttpServletRequest httpServletRequest) {
        try {
            var violations = validator.validate(request);
            if (!violations.isEmpty()) {
                List<Map<String, Object>> violationHeaderList = new ArrayList<>();
                List<String> validateHeader = new ArrayList<>();
                for (var violation : violations) {
                    logger.error(violation.getMessage());
                    Map<String, Object> data = new HashMap<>();
                    validateHeader.add(violation.getMessage());
                    data.put(violation.getPropertyPath().toString(), violation.getMessage());
                    violationHeaderList.add(data);
                }
                ResponseObject result = new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.BAD_REQUEST, validateHeader.get(0), violationHeaderList);
                return new ResponseEntity<>(result, result.getHttpCode());
            }

            Optional<M_METER_READING_CODES> mMeter = meterRepo.findByMeterReadingCodeId(request.getMeterReadingCodeId());
            if (mMeter.isPresent()) {
                if (meterRepo.existsByCodeIgnoreCaseAndCostCenterId(removeSpace(request.getCode()), UserDetailUtils.getPositionFromToken(httpServletRequest))) {
                    return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.BAD_REQUEST,
                            "Meter Reading Codes already exist!", ResponseUtils.DATA_EMPTY), HttpStatus.BAD_REQUEST);
                }
            } else {
                return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.NOT_FOUND,
                        UtilsAccount.messageDataNotFound(ConstantAccount.MASTER_METERREADINGCODE, request.getMeterReadingCodeId()), ResponseUtils.DATA_EMPTY), HttpStatus.NOT_FOUND);
            }

            return UtilsAccount.returnForValidateOrApi(api, ConstantAccount.MASTER_METERREADINGCODE);

        } catch (Exception e) {
            logger.error(Constant.LOG_ERROR, e.getMessage(), e);
            return new ResponseEntity<>(
                    new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.INTERNAL_SERVER_ERROR,
                            ResponseUtils.MESSAGE_INTERNAL_SERVER_ERROR, null),
                    HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    public ResponseEntity<ResponseObject> listCostCenter(HttpServletRequest httpServletRequest){
        try{
            CostCenterUtils costCenterUtils = new CostCenterUtils();
            List<NameValueDdlResponseDto> nameValueDdlResponseDtos = new ArrayList<>();
            Integer positionId = null;

            var checkUser = mUserRepo.findByUserId(Integer.parseInt(UserDetailUtils.getUserId()));
            if(checkUser.isEmpty()){
                return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.BAD_REQUEST, ResponseUtils.MESSAGE_BAD_REQUEST, ResponseUtils.DATA_EMPTY), HttpStatus.BAD_REQUEST);
            }

            if(!checkUser.get().getUserLevel().equalsIgnoreCase("SU")){
                positionId = UserDetailUtils.getPositionFromToken(httpServletRequest);
            }
            if(!ObjectUtils.isEmpty(positionId)){
//                Integer ccId = costCenterUtils.findCostCenterByPositionId(positionId);
                List<Integer> ccList = costCenterUtils.findCostCenterByPositionId(positionId, GET_CC_CHILD);

                List<M_COSTCENTER> costCenterData = mCostCenterRepo.findAllByCcIdIn(ccList);
                for (M_COSTCENTER cc : costCenterData){
                    NameValueDdlResponseDto nameValueDdlResponseDto = new NameValueDdlResponseDto();
                    nameValueDdlResponseDto.setName(cc.getCode()+" - "+cc.getName());
                    nameValueDdlResponseDto.setValue(cc.getCcId());
                    nameValueDdlResponseDtos.add(nameValueDdlResponseDto);
                }
            }else{
                List<M_COSTCENTER> mCostcenterList = mCostCenterRepo.findAll();
                if(!mCostcenterList.isEmpty()){
                    mCostcenterList.forEach(mCostcenter -> {
                        NameValueDdlResponseDto nameValueDdlResponseDto = new NameValueDdlResponseDto();
                        nameValueDdlResponseDto.setName(mCostcenter.getName());
                        nameValueDdlResponseDto.setValue(mCostcenter.getCcId());
                        nameValueDdlResponseDtos.add(nameValueDdlResponseDto);
                    });
                }
            }
            return new ResponseEntity<>(new ResponseObject(ResponseUtils.SUCCESS_TRUE, HttpStatus.OK,
                    ResponseUtils.MESSAGE_OK, nameValueDdlResponseDtos), HttpStatus.OK);
        }catch (Exception e){
            logger.error(Constant.LOG_ERROR, e.getMessage(), e);
            return new ResponseEntity<>(
                    new ResponseObject(ResponseUtils.SUCCESS_FALSE, HttpStatus.INTERNAL_SERVER_ERROR,
                            ResponseUtils.MESSAGE_INTERNAL_SERVER_ERROR, null),
                    HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
}
